apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    app: nginx-website
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007  # External port
